[package]
name = "koto"
version = "0.1.0"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
cpal = "0.8.2"
fuse = "0.3.1"
libc = "0.2.62"
num = "0.2"
rand = "0.6"
time = "0.1.42"
users = "0.9.1"
